name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # 每天UTC时间0点运行（北京时间8点）
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 关键！获取完整提交历史

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake.svg
            assets/snake-dark.svg?palette=github-dark
          # 强制更新参数
          force_update: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/snake*
          git commit -m "Update contribution snake" || echo "No changes to commit"
          git push
